"""
Phase 4 Step 6: apply_patch tool — 代码差异应用工具。

将 PatchApplier 包装为 BaseTool，让 LLM Agent 可以精准应用 unified diff。
与 Phase 1-2 的 write_file 工具互补——write_file 适合创建新文件，apply_patch 适合增量修改。

安全机制与 is_dangerous：
  - 标记为危险操作（修改磁盘文件）
  - Phase 2 先打黄色警告，Phase 9 接入用户审批
  - 工具内部有备份/恢复机制（.bak 文件）
"""

from app.tools.base import BaseTool, ToolResult         # 工具基类和返回格式
from app.coding.patch_apply import PatchApplier         # Patch 应用器


class ApplyPatchTool(BaseTool):
    """
    Patch 应用工具 —— 将 unified diff 应用到实际文件。

    与 write_file 的区别：
      - write_file: 覆盖整个文件（适合创建新文件）
      - apply_patch: 只改差异行（适合修改已有文件，更安全、更精准）
    """

    name = "apply_patch"

    description = (
        "Apply a unified diff patch to a file. "
        "Use this for incremental changes to existing files (safer than write_file). "
        "The diff must be in unified format (as generated by generate_diff). "
        "A backup is created automatically before applying (.bak file)."
    )

    @property
    def is_dangerous(self) -> bool:
        return True                      # 修改磁盘文件 —— 需用户确认

    @property
    def input_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "diff_text": {
                    "type": "string",
                    "description": "The unified diff text to apply (from generate_diff).",
                },
                "working_dir": {
                    "type": "string",
                    "description": "Working directory (base path for the diff). Default: current directory.",
                },
            },
            "required": ["diff_text"],
        }

    async def execute(self, diff_text: str, working_dir: str = ".",
                      **kwargs) -> ToolResult:
        try:
            applier = PatchApplier(backup=True)  # 自动创建备份
            result = applier.apply(diff_text, working_dir)

            if result.success:
                return ToolResult(
                    success=True,
                    message=(
                        f"Patch applied successfully to {result.file_path}\n"
                        f"Hunks applied: {result.hunks_applied}/{result.hunks_applied + result.hunks_failed}\n"
                        f"Backup saved to: {result.backup_path}\n"
                        f"Applied by: {result.applied_by}"
                    ),
                    metadata={
                        "file": result.file_path,
                        "hunks_applied": result.hunks_applied,
                        "backup": result.backup_path,
                        "method": result.applied_by,
                    },
                )
            else:
                # 构建详细的失败报告
                error_msg = f"Patch failed: {result.error_message}\n"
                if result.hunk_details:
                    for h in result.hunk_details:
                        if not h.applied:
                            error_msg += f"  - Hunk {h.header[:60]}: {h.error}\n"
                return ToolResult(success=False, message="", error=error_msg)

        except Exception as e:
            return ToolResult(success=False, message="", error=str(e))
